#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear + c.magenta + 'LETS TEST HOW FABILOOS U ARE, YYYYAAAAAAAYYYYY!!!' + c.reset)

print(c.clear + c.orange + 'WHAT COLOR WERE THE FABILOOS UNICORNS?' + c.reset) 

