#!/usr/bin/env python3
import random
import colors as c
import pink as quiz
print(c.clear + quiz.intro)

#YOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLOLO NARWHALS = SWAGGY
#SELFIE

while quiz.questions:
    if  random.choice(quiz.questions)():
        quiz.questions.remove(question_function)
    

