#!/usr/bin/env python3

import colors as c
import utils
import random

print(c.clear + c.magenta + "welcome to the wonderful quiz :}")

print(c.clear + c.red +" what is my favorite color?")
q1 = input("-->")

if q1 == "purple":  
    print(c.clear + c.orange + "yes")
else:    
    print("wrong!!!")


print(c.clear + c.green + "what year was i born in?")
q2 = input("-->")

if q2 == "2003":
    print(c.clear + c.magenta + "correct")
else:
    print(c.clear + c.red + "INCORRECT, YOU ARE NOW DEAD")

print(c.clear + c.blue + "are mooses swag?")
q3 = input("-->")

if q3 == "yes":
    print(c.clear + c.blue + "correct")    
else:
    print(c.clear + c.red + "incorrect")


print(c.clear + c.magenta + "what is my name?")
q4 = input("-->")

if q4 == "louisthegreat":
    print(c.clear + c.magenta + "yay, ur correct")
else:
    print(c.clear + c.magenta + "NOPE")













