#!/usr/bin/env python3

import colors as c
import utils
import random

print(c.clear + c.magenta + "welcome to the wonderful quiz :}
control c if u give up m80")

print(c.clear + c.red +" what is your favorite color?"
q1 = input("-->")

if q1 == else:  
    print(c.clear + c.orange + "WRONG"













